baseURL = "/"
languageCode = "en-gb"
title = "North of England Lhasa Apso Club"


[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

[outputs]
  home = ["HTML", "RSS", "JSON"]
