[[main]]
  name = "The Breed"
  identifier = "breed"
  url = "/breed/"
  weight = 20

[[main]]
  name = "Standard"
  url = "/breed/standard/"
  parent = "breed"
  weight = 1

[[main]]
  name = "Grooming"
  url = "/breed/grooming/"
  parent = "breed"
  weight = 2

[[main]]
  name = "History"
  url = "/breed/history/"
  parent = "breed"
  weight = 3

[[main]]
  name = "Health"
  url = "/breed/health/"
  parent = "breed"
  weight = 4

[[main]]
  name = "News"
  url = "/blog/"
  weight = 25

[[main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 30

[[main]]
  name = "Community"
  identifier = "community"
  url = "/community/"
  weight = 40

[[main]]
  name = "Breeders"
  url = "/community/breeders/"
  parent = "community"
  weight = 1

[[main]]
  name = "Member's Lounge"
  url = "/community/lounge/"
  parent = "community"
  weight = 2

[[main]]
  name = "Rescue"
  url = "/community/rescue/"
  parent = "community"
  weight = 3

[[main]]
  name = "Shows"
  url = "/calendar/"
  weight = 50

[[main]]
  name = "Judges"
  url = "/education/"
  weight = 60

[[main]]
  name = "Club Info"
  identifier = "club-info"
  url = "/club-info/"
  weight = 70

[[main]]
  name = "About"
  url = "/club-info/about/"
  parent = "club-info"
  weight = 1

[[main]]
  name = "Timeline"
  url = "/club-info/timeline/"
  parent = "club-info"
  weight = 2

[[main]]
  name = "Membership"
  url = "/club-info/join/"
  parent = "club-info"
  weight = 3

[[main]]
  name = "Code of Ethics"
  url = "/club-info/ethics/"
  parent = "club-info"
  weight = 4

[[main]]
  name = "FAQs"
  url = "/club-info/faq/"
  parent = "club-info"
  weight = 5

[[main]]
  name = "Useful Links"
  url = "/club-info/useful-links/"
  parent = "club-info"
  weight = 6
