disableTextInHeader = true
colorScheme = "noelac"
logo = "logo.webp"
secondaryLogo = "logo.png"

[calendar_config]
calendar_provider = "google"
calendar_view = "listMonth"
show_calendar = true
calendar_id = "c_ab07c807fc5701020f6f214de33dc53f75ef36f78b19fe548f8acd537d651448@group.calendar.google.com"

[search]
showExcerpt = true
showSubTitle = true
showResultCount = true
showClearButton = true

[header]
layout = "fixed"
showLogo = true
showTitle = false

[[social]]
name = "facebook"
icon = "facebook"
link = "https://www.facebook.com/lhasaclub"

[[social]]
name = "instagram"
icon = "instagram"
link = "https://instagram.com/noelac"

[[social]]
name = "bluesky"
icon = "bluesky"
link = "https://bsky.app/profile/noelac.org"

[[social]]
name = "youtube"
icon = "youtube"
link = "https://youtube.com"

[homepage]
layout = "hero"
homepageImage = "20260402_115338(1).jpg"
showRecentPosts = true

[article]
showTableOfContents = false
smartTOC = true
showDate = false
showDateUpdated = false
showWordCount = false
showReadingTime = false
showAuthor = true
showTags = false

[footer]
showThemeAttribution = false
showSocial = true
calendar_provider = "google"
calendar_id = ""
calendar_view = "dayGridMonth"
show_calendar = true

[list]
showDate = false
showSummary = true
showRecent = false
cardView = true
