colorScheme = "noelac"

[homepage]
  layout = "hero"
  # Ensures Hero style is used
  homepageImage = "hero-winner.jpg"
  showRecentPosts = true

[header]
  layout = "fixed"

[footer]
  showThemeAttribution = false
  showSocial = true

[article]
  showTableOfContents = false
  smartTOC = true
  showDate = false
  showDateUpdated = false
  showWordCount = false
  showReadingTime = false
  showAuthor = false
  showTags = false

[search]
  showExcerpt = true
  showSubTitle = true
  showResultCount = true
  showClearButton = true

[[social]]
  name = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/lhasaclub"

[[social]]
  name = "instagram"
  icon = "instagram"
  link = "https://instagram.com/noelac"

[[social]]
  name = "bluesky"
  icon = "bluesky"
  link = "https://bsky.app"

[[social]]
  name = "youtube"
  icon = "youtube"
  link = "https://youtube.com"
